name: run-htmltest
on: pull_request
jobs:
  htmltest:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
      - name: Build Hugo
        run: hugo -s site -d $GITHUB_WORKSPACE/dist
      - name: Test HTML
        continue-on-error: false
        uses: wjdp/htmltest-action@master
        with:
          config: .htmltest.yml
      - name: Archive htmltest results
        uses: actions/upload-artifact@v2
        with:
          name: htmltest-report
          path: tmp/.htmltest/htmltest.log
          retention-days: 7
